

source 'https://rubygems.org' do
  gem 'sinatra'
  gem 'sinatra-reloader'
  gem 'sinatra-flash'
  gem 'slim'
  gem 'sass'
  gem 'thin'
  gem 'logger'


  group :production do

  end

  group :development do

  end
end